#!/usr/bin/env bash

set -euo pipefail

OS="$(uname -s)"

if [[ "$OS" == "Linux" ]]; then
    pushd ~/personal/dev/env/.config/nvim || exit
    git add .
    git commit -m 'automated dev commit'
    git push
    popd || exit

    pushd ~/personal/dev || exit
    git add .
    git commit -m 'automated dev commit'
    git push
    popd || exit
elif [[ "$OS" == "Darwin" ]]; then
    pushd ~/personal/dev || exit
    git add .
    git commit -m 'automated dev commit'
    git push
    popd || exit
fi
